name: cu-valley-slag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - lightgbm
  - neptune-client
  - pandas
  - pillow
  - plotly
  - scikit-learn
  - shap
  - streamlit
  - tsfresh
  - xgboost
  - yaml