dataset:
  columns:
    temperature: temp
    time: czas
  directory: ../resources/dataset
  features: 176
  filenames:
    test: test.csv
    train: train.csv
  window_size: 5
model:
  config_file: ../resources/cfg/models/XGBoost.yaml
  name: XGBoost
serialization:
  directory: ../output/models
