dataset:
  columns:
    temperature: temp
    time: czas
  directory: ../resources/dataset
  features: 20
  filenames:
    test: test.csv
    train: ../dataset_30_small.csv
  window_size: 30
model:
  config_file: ../resources/cfg/models/XGBoost.yaml
  name: XGBoost
serialization:
  directory: ../output/models
